aktienExamen/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Linq;
using System.Web;
using System.Web.Mvc;
using Aktien.Libraries.Structs;
using aktienExamen.Models;

namespace aktienExamen.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        clientesDataContext db = new clientesDataContext(@"data source=MARIBEL\SQLEXPRESS;initial catalog=DBclientes;integrated security=True");

        public ActionResult Index()
        {
            IList<Cliente> listaClientes = new List<Cliente>();
            var query = from c in db.clientes select c;
            var listadata = query.ToList();

            foreach (var clientedata in listadata)
            {
                listaClientes.Add(new Cliente()
                {
                    num_cliente = clientedata.num_cliente,
                    nombre = clientedata.nombre,
                    apellido_paterno = clientedata.apellido_paterno,
                    apellido_materno = clientedata.apellido_materno,
                    telefono = clientedata.telefono,
                    tipos_cliente = clientedata.tipos_cliente,

                });
            }
            return View("ListarClientes");

        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {

            return View("CreateCliente");
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                //db.clientes.InsertOnSubmit(collection);
                db.SubmitChanges();

                return RedirectToAction("CreateCliente");
            }
            catch
            {
                return View("CreateCliente");
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Edit(int num_cliente, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                //Cliente c = db.clientes.Single(x => x.num_cliente == num_cliente);
                //c.nombre = collection.nombre;
                //c.apellido_paterno = collection.empfathername;
                //c.apellido_materno = collection.empsalary;
                //c.telefono = collection.tel;
                //c.tipos_cliente = collection.tipo;
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int num_cliente)
        {
            var cliente = db.clientes.Single(x => x.num_cliente == num_cliente);
            return View();
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public ActionResult Delete(int num_cliente, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var cliente = db.clientes.Single(x => x.num_cliente == num_cliente);
                db.clientes.DeleteOnSubmit(cliente);
                db.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

aktienExamen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aktienExamen.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

aktienExamen/Controllers/TipoClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aktienExamen.Controllers
{
    public class TipoClienteController : Controller
    {
        // GET: TipoCliente
        public ActionResult Index()
        {
            return View("ListTipoCliente");
        }

        // GET: TipoCliente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoCliente/Create
        public ActionResult Create()
        {
            return View("CreateTipoCliente");
        }

        // POST: TipoCliente/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoCliente/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TipoCliente/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoCliente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TipoCliente/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

aktienExamen/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

aktienExamen/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div id="wrapper">
                <div id="sidebar-wrapper">
                    <aside id="sidebar">
                        <ul id="sidemenu" class="sidebar-nav">
                            <li>
                                <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse" href="#submenu-1">
                                    <span class="sidebar-icon"><i class="fa fa-users"></i></span>
                                    <span class="sidebar-title">Clientes</span>
                                    <b class="caret"></b>
                                </a>
                                <ul id="submenu-1" class="panel-collapse collapse panel-switch" role="menu">
                                    <li>
                                        <a class="w3-bar-item w3-button"><i class="fa fa-caret-right"></i>@Html.ActionLink("Listar Clientes", "Index", "Cliente")</a>
                                    </li>
                                    <li>
                                        <a class="w3-bar-item w3-button">@Html.ActionLink("Nuevo Cliente", "Create", "Cliente")</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse"  href="#submenu-2">
                                    <span class="sidebar-icon"><i class="fa fa-database"></i></span>
                                    <span class="sidebar-title">Tipos Clientes</span>
                                    <b class="caret"></b>
                                </a>
                                <ul id="submenu-2" class="panel-collapse collapse panel-switch" role="menu">
                                    <li>
                                        <a class="w3-bar-item w3-button"><i class="fa fa-caret-right"></i>@Html.ActionLink("Listar Tipos Cliente", "Index", "TipoCliente")</a>
                                    </li>
                                    <li>
                                        <a class="w3-bar-item w3-button">@Html.ActionLink("Nuevo Tipo Cliente", "Create", "TipoCliente")</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div> <!-- .column is 3 -->

            <div class="col-md-9" style="margin-left:15%">
                <div class="w3-container w3-teal">
                    <h1>Examen .Net</h1>
                </div>

                <div class="w3-container">
                    <h2>AKTIEN</h2>
                    <p>Maribel Barrera Tabares.</p>
                </div>
            </div>
        </div>
</div>